[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Federico Vega - HP", email = "federico_Vega22@hotmail.com"},
]
dependencies = [
    "django>=4.2.4",
    "django-pwa>=1.1.0",
    "apscheduler>=3.10.4",
    "requests>=2.31.0",
    "aiohttp>=3.8.5",
    "Pillow>=10.0.0",
]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

