[tool.pdm]

[project]
name = "Regionales"
version = "0.1.0"
description = "A Web App for my own business"
authors = [
    {name = "DarthKenar", email = "federico_vega22@hotmail.com"},
]
dependencies = [
    "django>=4.1.7",
    "psycopg2>=2.9.5",
]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-pep517>=1.0"]
build-backend = "pdm.pep517.api"
