# Generated by Django 4.2.4 on 2023-09-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='total_purchased',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True),
        ),
    ]
