flowchart TB
  subgraph "header.html"
    direction TB
    A[["articles.html"]]
    C[["customers.html"]]
    O[["orders.html"]]
  end
  subgraph BODY
    direction TB
    L[["login.html"]] -->|loggin required| HOME[["home.html"]]

  end
  subgraph "articles.html"
    direction TB
    a(asdsWWWs)
  end
  subgraph "customers.html"
    direction TB
    j(asdsasds)
  end
  subgraph "orders.html"
    direction TB
    t(assdss)
  end
  header.html -..-|include| HOME
  A -----> articles.html
  C -----> customers.html
  O -----> orders.html