# Generated by Django 4.2.3 on 2023-08-01 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('articles', '0006_remove_order_article_id_remove_order_customer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_quantity', models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='Articles Quantity')),
                ('total_pay', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Total pay')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Details')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Date last modified')),
                ('delivery_status', models.BooleanField(default=False, verbose_name='Delivery status')),
                ('article_id', models.ManyToManyField(through='orders.ArticleOrder', to='articles.article', verbose_name='Articles')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['customer_id'],
            },
        ),
        migrations.AddField(
            model_name='articleorder',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
