# Generated by Django 4.2.4 on 2023-09-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_article_name'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='article_id',
            field=models.ManyToManyField(related_name='articles_cart', through='orders.ArticleOrder', to='articles.article', verbose_name='Articles'),
        ),
        migrations.AlterField(
            model_name='order',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Delivery status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date last modified'),
        ),
    ]
