# Generated by Django 4.2.4 on 2023-09-09 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_article_id_alter_order_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleorder',
            options={'ordering': ['order_id'], 'verbose_name': 'ArticleOrder', 'verbose_name_plural': 'ArticleOrders'},
        ),
    ]
