# Generated by Django 4.2.4 on 2023-09-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_articleorder_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='article_id',
            new_name='articles_cart',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Delivery status'),
        ),
    ]
