# Generated by Django 4.1.5 on 2023-02-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articulos_proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32, verbose_name='Nombre del artículo')),
                ('tipo', models.CharField(max_length=32, verbose_name='Tipo de producto')),
                ('color', models.CharField(blank=True, max_length=32, null=True, verbose_name='Color')),
                ('material', models.CharField(blank=True, max_length=32, null=True, verbose_name='Material')),
                ('precio', models.IntegerField(verbose_name='Precio')),
            ],
        ),
    ]
