# Generated by Django 4.1.7 on 2023-02-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Promos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32, verbose_name='Nombre')),
                ('tipo', models.CharField(max_length=32, verbose_name='Tipo')),
                ('color', models.CharField(blank=True, choices=[(1, 'verde'), (2, 'bordó'), (3, 'azul'), (4, 'negra'), (5, 'blanca'), (6, 'beige')], max_length=32, null=True, verbose_name='Color')),
                ('material', models.CharField(blank=True, max_length=32, null=True, verbose_name='Material')),
                ('talle', models.IntegerField(blank=True, null=True, verbose_name='Talle')),
                ('precio_compra', models.FloatField(verbose_name='Precio de Compra')),
                ('incremento', models.FloatField(verbose_name='Incremento del Precio')),
                ('precio_venta', models.FloatField(verbose_name='Precio de Venta')),
            ],
        ),
        migrations.DeleteModel(
            name='articulos_proveedor',
        ),
    ]
