# Generated by Django 4.1.7 on 2023-02-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_gastos_pedidos_promos_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='color',
            field=models.CharField(blank=True, choices=[('VDE', 'verde'), ('BDO', 'bordó'), ('AZL', 'azul'), ('NRA', 'negra'), ('BCA', 'blanca'), ('BGE', 'beige')], max_length=32, null=True, verbose_name='Color'),
        ),
    ]
