# Generated by Django 4.1.3 on 2023-03-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=32, verbose_name='Correo Electrónico')),
                ('phone_number', models.CharField(max_length=32, verbose_name='numero de teléfono')),
                ('password', models.CharField(max_length=32, verbose_name='Password')),
            ],
        ),
    ]
