# Generated by Django 4.1.5 on 2023-02-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32, verbose_name='Nombre')),
                ('correo', models.EmailField(max_length=32, verbose_name='Correo Electrónico')),
                ('contrasenia', models.CharField(max_length=32, verbose_name='Password')),
            ],
        ),
    ]
