# Generated by Django 4.2.4 on 2023-08-30 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userprofileextends_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileextends',
            name='profile_picture',
            field=models.ImageField(blank=True, default='', null=True, upload_to='img/profile-pictures/'),
        ),
    ]
