# Generated by Django 4.2.4 on 2023-08-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_userprofileextends_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileextends',
            name='profile_picture',
            field=models.ImageField(blank=True, default='', null=True, upload_to='profile-pictures'),
        ),
    ]
