# Generated by Django 4.2.4 on 2023-09-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_userprofileextends_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileextends',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default-profile-picture.png', null=True, upload_to='profile-pictures'),
        ),
    ]
