# Generated by Django 4.2.4 on 2023-09-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_userprofileextends_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileextends',
            name='profile_picture',
            field=models.ImageField(blank=True, default='elcanarioregionales-logo-160x160.png', null=True, upload_to='profile-pictures'),
        ),
    ]
