# Generated by Django 4.2.4 on 2023-09-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageslog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagelog',
            options={'ordering': ['date'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='info',
            field=models.TextField(max_length=500),
        ),
    ]
