# Generated by Django 4.2.4 on 2023-09-04 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messageslog', '0002_alter_messagelog_options_alter_messagelog_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagelog',
            options={'ordering': ['-date'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
    ]
