# Generated by Django 4.1.3 on 2023-03-06 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=32, verbose_name='Nombre')),
                ('buy_price', models.FloatField(verbose_name='$ COMPRA')),
                ('increase', models.FloatField(default=1.7, help_text='Numero que hace referencia al porcentaje de incremento', verbose_name='Incremento del Precio')),
                ('sell_price', models.FloatField(help_text='Es el resultante del precio de compra multiplicado su incremento.', verbose_name='$ VENTA')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['article_name', 'category_id'],
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30, unique=True, verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=30, unique=True, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colores',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=32, verbose_name='Cliente')),
                ('phone_number', models.CharField(help_text='Este es un campo de texto en el cual se debe ingresar el numero de teléfono del cliente', max_length=32, verbose_name='Numero de Teléfono')),
                ('address', models.CharField(blank=True, default='Avenida siempre viva', help_text='Este es un campo de texto en el cual se debe ingresar el domicilio del cliente', max_length=128, null=True, verbose_name='Domicilio')),
                ('email', models.EmailField(blank=True, default='nombre@correo.com', max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('total_purchased', models.FloatField(blank=True, default=0, editable=False, null=True, verbose_name='Total Comprado')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['customer_name'],
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=32, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, help_text='breve descripción del gasto si fuese necesario. *Campo NO obligatorio', max_length=128, null=True, verbose_name='Descripcion')),
                ('quantity', models.PositiveSmallIntegerField(default=1, help_text='Cantidad de productos comprados', verbose_name='Cantidad')),
                ('total_cost', models.FloatField(help_text='Precio de compra del producto adquirido.', verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['total_cost', 'expense_name'],
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=30, unique=True, verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
            },
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=32, unique=True, verbose_name='Talle')),
            ],
            options={
                'verbose_name': 'Talle',
                'verbose_name_plural': 'Talles',
            },
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveSmallIntegerField(verbose_name='Existencias')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.articles', unique=True, verbose_name='Artículo')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ['article_id', 'stock'],
            },
        ),
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_name', models.CharField(max_length=32, verbose_name='Nombre')),
                ('discount', models.FloatField(verbose_name='Descuento')),
                ('sell_price', models.FloatField(verbose_name='$ VENTA')),
                ('articles_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.articles', verbose_name='Productos')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'ordering': ['promotion_name', 'articles_id'],
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articles_quantity', models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='Cantidad de Artículos')),
                ('total_pay', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Total a pagar')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('delivery_status', models.BooleanField(default=False, verbose_name='Estado de la entrega')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.articles', verbose_name='Artículos')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.customers', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['customer_id'],
            },
        ),
        migrations.AddField(
            model_name='articles',
            name='category_id',
            field=models.ForeignKey(blank=True, max_length=32, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='articles.categories', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='articles',
            name='color_id',
            field=models.ForeignKey(blank=True, max_length=32, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='articles.colors', verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='articles',
            name='material_id',
            field=models.ForeignKey(blank=True, max_length=32, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='articles.materials', verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='articles',
            name='size_id',
            field=models.ForeignKey(blank=True, max_length=32, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='articles.sizes', verbose_name='Talle'),
        ),
    ]
