# Generated by Django 4.1.3 on 2023-07-18 19:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DollarGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('price', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['name'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='articlevalue',
            options={'verbose_name': 'Values and articles Categories', 'verbose_name_plural': 'Values and articles Categories'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['total_cost'], 'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['customer_id'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['sell_price'], 'verbose_name': 'Promotion', 'verbose_name_plural': 'Promotions'},
        ),
        migrations.AlterModelOptions(
            name='value',
            options={'ordering': ['name'], 'verbose_name': 'Value', 'verbose_name_plural': 'Values'},
        ),
        migrations.AlterField(
            model_name='article',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Buy price'),
        ),
        migrations.AlterField(
            model_name='article',
            name='increase',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Increment'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='article',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Sell price'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, max_length=128, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='article_id',
            field=models.ManyToManyField(through='articles.ArticleOrder', to='articles.article', verbose_name='Articles'),
        ),
        migrations.AlterField(
            model_name='order',
            name='article_quantity',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='Articles Quantity'),
        ),
        migrations.AlterField(
            model_name='order',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.BooleanField(default=False, verbose_name='Delivery status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_pay',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Total pay'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date last modified'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='article_id',
            field=models.ManyToManyField(through='articles.ArticlePromotion', to='articles.article', verbose_name='Articles'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='remainder',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Remaining amount'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='$ SALE'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='article_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.article', verbose_name='Article'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Stock'),
        ),
    ]
