# Generated by Django 4.2.3 on 2023-07-18 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_dollargraph_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DollarGraph',
        ),
    ]
