# Generated by Django 4.2.3 on 2023-08-01 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_delete_dollargraph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='article_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_id',
        ),
        migrations.DeleteModel(
            name='ArticleOrder',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
