# Generated by Django 4.2.3 on 2023-08-01 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_remove_order_article_id_remove_order_customer_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
