# Generated by Django 4.2.4 on 2023-08-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_delete_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='stock',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
