# Generated by Django 4.2.4 on 2023-09-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles'),
        ),
        migrations.AlterField(
            model_name='article',
            name='stock',
            field=models.PositiveSmallIntegerField(verbose_name='Stock'),
        ),
    ]
